[build]
  base = "netlify/"
  publish = "build/site/"
  command = "node_modules/.bin/antora --stacktrace --fetch --html-url-extension-style=indexify ../site.yml"

[build.environment]
  NODE_VERSION = "10"
  BUILD_ONLY = "true"
  ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.deploy-preview]
  command = "node_modules/.bin/antora --stacktrace --fetch --html-url-extension-style=indexify --url $DEPLOY_PRIME_URL ../site.yml"
